export default [
  {name:"scifiButtonA1",
    desc:"",
    children:[
      {button:"scifiButtonA1",text:"ButtonText",config:{ 
        backgroundOpacity:.5
      }},
      {button:"scifiButtonA1",text:"ButtonActive",config:{
        className:"is-active"
      }},
      {button:"scifiButtonA1",text:"ButtonDisabled",config:{
        disabled:true
      }},
      {button:"scifiButtonA1",text:"ButtonLarge",config:{
        size:"large",
        glowOpacity:1
      }},
      {button:"scifiButtonA1",text:"ButtonSmall",config:{
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
        glowOpacity:1
      }},
      {button:"scifiButtonA1",text:"ButtonCustom",config:{
        className:"sfb-custom",
        backgroundOpacity:.5
      }},

      {button:"scifiButtonA1",text:"ButtonText Long",config:{
        appearance:"B",
      }},
      {button:"scifiButtonA1",text:"ButtonActive",config:{
        appearance:"B",
        className:"is-active"
      }},
      {button:"scifiButtonA1",text:"ButtonDisabled",config:{
        appearance:"B",
        disabled:true
      }},
      {button:"scifiButtonA1",text:"ButtonLarge",config:{
        appearance:"B",
        size:"large",
      }},
      {button:"scifiButtonA1",text:"ButtonSmall",config:{
        appearance:"B",
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA1",text:"ButtonCustom",config:{
        appearance:"B",
        className:"sfb-custom",
      }},

      {button:"scifiButtonA1",text:"ButtonText",config:{
        appearance:"C",
      }},
      {button:"scifiButtonA1",text:"ButtonActive",config:{
        appearance:"C",
        className:"is-active"
      }},
      {button:"scifiButtonA1",text:"ButtonDisabled",config:{
        appearance:"C",
        disabled:true
      }},
      {button:"scifiButtonA1",text:"ButtonLarge",config:{
        appearance:"C",
        size:"large",
      }},
      {button:"scifiButtonA1",text:"Small",config:{
        appearance:"C",
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA1",text:"ButtonCustom",config:{
        appearance:"C",
        className:"sfb-custom",
        disabled:true
      }},
      {button:"scifiButtonA1",text:"GlowLess",config:{ glow:false,}},
    ]
  },
  {name:"scifiButtonA2",
    desc:"",
    children:[
      {button:"scifiButtonA2",text:"ButtonText",config:{ }},
      {button:"scifiButtonA2",text:"ButtonActive",config:{
        className:"is-active"
      }},
      {button:"scifiButtonA2",text:"ButtonDisabled",config:{
        disabled:true
      }},
      {button:"scifiButtonA2",text:"ButtonLarge",config:{
        size:"large",
        glowOpacity:1
      }},
      {button:"scifiButtonA2",text:"ButtonSmall",config:{
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
        glowOpacity:1
      }},
      {button:"scifiButtonA2",text:"ButtonCustom",config:{
        className:"sfb-custom",
      }},

      {button:"scifiButtonA2",text:"ButtonText",config:{
        appearance:"B",
      }},
      {button:"scifiButtonA2",text:"ButtonActive",config:{
        appearance:"B",
        className:"is-active"
      }},
      {button:"scifiButtonA2",text:"ButtonDisabled",config:{
        appearance:"B",
        disabled:true
      }},
      {button:"scifiButtonA2",text:"ButtonLarge",config:{
        appearance:"B",
        size:"large",
      }},
      {button:"scifiButtonA2",text:"ButtonSmall",config:{
        appearance:"B",
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA2",text:"ButtonCustom",config:{
        appearance:"B",
        className:"sfb-custom",
      }},

      {button:"scifiButtonA2",text:"GlowLess",config:{ glow:false,}},
    ]
  },
  
  {name:"scifiButtonA3",
    desc:"",
    children:[
      {button:"scifiButtonA3",text:"ButtonText",config:{ }},
      {button:"scifiButtonA3",text:"ButtonActive",config:{
        className:"is-active"
      }},
      {button:"scifiButtonA3",text:"ButtonDisabled",config:{
        disabled:true
      }},
      {button:"scifiButtonA3",text:"ButtonLarge",config:{
        size:"large",
        glowOpacity:1
      }},
      {button:"scifiButtonA3",text:"ButtonSmall",config:{
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
        glowOpacity:1
      }},
      {button:"scifiButtonA3",text:"ButtonCustom",config:{
        className:"sfb-custom",
      }},

      {button:"scifiButtonA3",text:"ButtonText",config:{
        appearance:"B",
      }},
      {button:"scifiButtonA3",text:"ButtonActive",config:{
        appearance:"B",
        className:"is-active"
      }},
      {button:"scifiButtonA3",text:"ButtonDisabled",config:{
        appearance:"B",
        disabled:true
      }},
      {button:"scifiButtonA3",text:"ButtonLarge",config:{
        appearance:"B",
        size:"large",
      }},
      {button:"scifiButtonA3",text:"ButtonSmall",config:{
        appearance:"B",
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA3",text:"ButtonCustom",config:{
        appearance:"B",
        className:"sfb-custom",
      }},

      {button:"scifiButtonA3",text:"GlowLess",config:{ glow:false,}},
    ]
  },
  
  
  {name:"scifiButtonA4",
    desc:"",
    children:[
      {button:"scifiButtonA4",text:"ButtonText",config:{ }},
      {button:"scifiButtonA4",text:"ButtonActive",config:{
        className:"is-active"
      }},
      {button:"scifiButtonA4",text:"ButtonDisabled",config:{
        disabled:true
      }},
      {button:"scifiButtonA4",text:"ButtonLarge",config:{
        size:"large",
      }},
      {button:"scifiButtonA4",text:"ButtonSmall",config:{
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA4",text:"ButtonCustom",config:{
        className:"sfb-custom",
      }},

      {button:"scifiButtonA4",text:"ButtonText",config:{
        appearance:"B",
      }},
      {button:"scifiButtonA4",text:"ButtonActive",config:{
        appearance:"B",
        className:"is-active"
      }},
      {button:"scifiButtonA4",text:"ButtonDisabled",config:{
        appearance:"B",
        disabled:true
      }},
      {button:"scifiButtonA4",text:"ButtonLarge",config:{
        appearance:"B",
        size:"large",
      }},
      {button:"scifiButtonA4",text:"ButtonSmall",config:{
        appearance:"B",
        decorationColorAlt:true,
        scaleAction:false,
        size:"small",
      }},
      {button:"scifiButtonA4",text:"ButtonCustom",config:{
        appearance:"B",
        className:"sfb-custom",
      }},

      {button:"scifiButtonA4",text:"GlowLess",config:{ glow:false,}},
    ]
  },
  
  
  {name:"scifiButtonA5",
    desc:"",
    children:[
      {button:"scifiButtonA5",text:"ButtonText",config:{
        
      }},
      {button:"scifiButtonA5",text:"ButtonActive",config:{
        className:"is-active"
      }},
      {button:"scifiButtonA5",text:"ButtonDisabled",config:{
        disabled:true
      }},
      {button:"scifiButtonA5",text:"ButtonLarge",config:{
        size:"large",
      }},
      {button:"scifiButtonA5",text:"ButtonSmall",config:{
        decorationColorAlt:true,
        size:"small",
      }},
      {button:"scifiButtonA5",text:"ButtonCustom",config:{
        directionAlt:true,
        className:"sfb-custom",
      }},


      {button:"scifiButtonA5",text:"ButtonText",config:{
        appearance:"B",
      }},
      {button:"scifiButtonA5",text:"ButtonActive",config:{
        appearance:"B",
        className:"is-active"
      }},
      {button:"scifiButtonA5",text:"ButtonDisabled",config:{
        appearance:"B",
        disabled:true
      }},
      {button:"scifiButtonA5",text:"ButtonLarge",config:{
        appearance:"B",
        size:"large",
      }},
      {button:"scifiButtonA5",text:"ButtonSmall",config:{
        appearance:"B",
        decorationColorAlt:true,
        size:"small",
      }},
      {button:"scifiButtonA5",text:"ButtonCustom",config:{
        appearance:"B",
        directionAlt:true,
        className:"sfb-custom",
      }},

      {button:"scifiButtonA5",text:"GlowLess",config:{ glow:false,}},
    ]
  },
]